version: '3.8'

services:
  db:
    container_name: chatbot_mysql
    build:
      context: ./mysql
      dockerfile: mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: broken_chatbot
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - mysqldb:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    networks:
      - broken_chatbot

  web:
    container_name: chatbot_backend
    build:
      context: ./backend
      dockerfile: web.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - broken_chatbot

  ui:
    container_name: chatbot_frontend
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
#    ports:
#      - "3000:3000"
    networks:
      - broken_chatbot

  nginx:
    container_name: chatbot_nginx
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - ui
    networks:
      - broken_chatbot

volumes:
  mysqldb:

networks:
  broken_chatbot:
    driver: bridge
